config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :veiculos
  resources :reservas
  root 'paginas#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reserva.rb
class Reserva < ApplicationRecord
    belongs_to :usuario
    belongs_to :veiculo
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_many :reservas
    has_many :veiculos
    
    validates :username, presence: true, 
                         uniqueness: { case_sensitive: false },
                         length: { minimum: 3, maximum: 25 }
                        
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
                          
    before_save { self.email = email.downcase }    
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
    belongs_to :usuario
    has_many :reservas
    
    validates :modelo, presence: true, length: { maximum: 30 }
    validates :marca, presence: true, length: { maximum: 30 }
    validates :ano, presence: true, length: { maximum: 4 }
    validates :placa, presence: true, length: { maximum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/paginas_controller.rb
# frozen_string_literal: true

class PaginasController < ApplicationController
  def home; end

  def about; end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: %i[ show edit update destroy ]

  # GET /reservas or /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1 or /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas or /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)
    @reserva.usuario = Usuario.first
    @reserva.veiculo = Veiculo.find(params['reserva']['veiculo_id'])
    respond_to do |format|
      if @reserva.save
        format.html { redirect_to reservas_path, notice: "A reserva foi criada com sucesso." }
        format.json { render :index, status: :created, location: @reserva }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1 or /reservas/1.json
  def update
    @reserva.veiculo = Veiculo.find(params['reserva']['veiculo_id'])
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to reservas_path, notice: "A reserva foi alterada com sucesso." }
        format.json { render :index, status: :ok, location: @reserva }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1 or /reservas/1.json
  def destroy
    @reserva.destroy

    respond_to do |format|
      format.html { redirect_to reservas_url, notice: "A reserva foi removida com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reserva_params
      params.require(:reserva).permit(:data_entrada, :data_saida, :hora_entrada, :hora_saida)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:username, :email)
    end
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: %i[ show edit update destroy ]

  # GET /veiculos or /veiculos.json
  def index
    @veiculos = Veiculo.all
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos or /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)
    @veiculo.usuario = Usuario.first
    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to veiculos_path, notice: "O veículo foi cadastrado com sucesso." }
        format.json { render :index, status: :created, location: @veiculo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1 or /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to veiculos_path, notice: "O veículo alterado com sucesso." }
        format.json { render :index, status: :ok, location: @veiculo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1 or /veiculos/1.json
  def destroy
    @veiculo.destroy

    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: "O veículo foi removido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def veiculo_params
      params.require(:veiculo).permit(:modelo, :marca, :ano, :placa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to 'Raphael Malinski Vieira', 'https://github.com/raphaelmalinski', class: 'text-white-50' %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container pt-2">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "PARKING AND RESERVATION", root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Reservas
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Criar nova reserva", new_reserva_path, class: "dropdown-item" %>
          <%= link_to "Visualizar reservas", reservas_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Veículos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Cadastrar veículo", new_veiculo_path, class: "dropdown-item" %>
          <%= link_to "Visualizar veículos", veiculos_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking and Reservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/paginas/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Parking and Reservation</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
      <a class="btn btn-success btn-lg" href="#" role="button">Inscrever-se</a>
    </p>
  </div>
</div>

app/views/reservas/_errors.html.erb
<% if @reserva&.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Os seguintes erros impedem que a reserva seja efetuada:</h4>
    <ul>
      <% @reserva.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/reservas/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-7">
      <%= render 'errors' %>
      <%= form_with(model: @reserva, class: 'shadow-light p-3 mb-3 bg-dark rounded', local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :data_entrada, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.date_select :data_entrada, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :data_saida, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.date_select :data_saida, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :hora_entrada, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.time_select :hora_entrada, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :hora_saida, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.time_select :hora_saida, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :veiculo_id, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.select(:veiculo_id, options_for_select(Usuario.first.veiculos.pluck(:modelo, :placa, :id).to_a.map { |v| ["#{v.first} (#{v.second})", v[2]] }), class: 'select-veiculos') %>
          </div>
        </div>
        <div class="form-group row justify-content-center mt-4">
          <%= f.submit 'Reservar', class: 'btn btn-outline-light btn-lg' %>
        </div>
      <% end %> 
      <div class="mb-4">
        <%= link_to '[ Cancelar ]', reservas_path, class: 'row justify-content-center text-dark' %>
      </div>
    </div>
  </div>
</div>

app/views/reservas/edit.html.erb
<h1 class="text-center mt-4">Editar Reserva</h1>

<%= render 'form', reserva: @reserva %>

app/views/reservas/index.html.erb
<h1 class="text-center mt-4">Minhas Reservas</h1>

<div class="container">
  <% @reservas.each do |reserva| %>
    <div class="row justify-content-md-center">
      <div class="col-7 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body text-left">
            <table>
              <tr>
                <td class="text-right pr-2"><strong>Data de entrada:</strong></td>
                <td><%= reserva.data_entrada.strftime("%d/%m/%Y") %></td>
              </tr>
              <tr>
                <td class="text-right pr-2"><strong>Data de saída:</strong></td>
                <td><%= reserva.data_saida.strftime("%d/%m/%Y") %></td>
              </tr>
              <tr>
                <td class="text-right pr-2"><strong>Hora de entrada:</strong></td>
                <td><%= reserva.hora_entrada.strftime("%d/%m/%Y %H:%M") %></td>
              </tr>
              <tr>
                <td class="text-right pr-2"><strong>Hora de saída:</strong></td>
                <td><%= reserva.hora_saida.strftime("%d/%m/%Y %H:%M") %></td>
              </tr>
              <tr>
                <td class="text-right pr-2"><strong>Veículo:</strong></td>
                <td><%= reserva.veiculo&.placa&.upcase %></td>
              </tr>
            </table>
            <div class="text-right mt-2">
              <%= link_to 'Editar', edit_reserva_path(reserva), class: 'btn btn-info' %>
              <%= link_to 'Excluir', reserva_path(reserva), class: 'btn btn-danger', 
                                    method: :delete, data: { confirm: "Tem certeza que deseja excluir essa reserva?" } %>
            </div>
          </div>
          
          <div class="card-footer text-muted">
            <small>
              Criado há <%= time_ago_in_words(reserva.created_at) %>, 
              modificado há <%= time_ago_in_words(reserva.updated_at) %>     
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reservas/new.html.erb
<h1 class="text-center mt-4">Nova Reserva</h1>

<%= render 'form', reserva: @reserva %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.username %></td>
        <td><%= usuario.email %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @usuario.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/veiculos/_errors.html.erb
<% if @veiculo&.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Os seguintes erros impedem que o veículo seja cadastrado:</h4>
    <ul>
      <% @veiculo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/veiculos/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-7">
      <%= render 'errors' %>
      <%= form_with(model: @veiculo, class: 'shadow-light p-3 mb-3 bg-dark rounded', local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :modelo, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.text_field :modelo, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :marca, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.text_field :marca, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :ano, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.number_field :ano, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :placa, class: 'col-3 col-form-label text-light' %>
          <div class="col-9">
            <%= f.text_field :placa, class: 'form-control shadow-light' %>
          </div>
        </div>
        
        <div class="form-group row justify-content-center mt-4">
          <%= f.submit 'Cadastrar Veículo', class: 'btn btn-outline-light btn-lg' %>
        </div>
      <% end %> 
      <div class="mb-4">
        <%= link_to '[ Cancelar ]', veiculos_path, class: 'row justify-content-center text-dark' %>
      </div>
    </div>
  </div>
</div>

app/views/veiculos/edit.html.erb
<h1 class="text-center mt-4">Editar Veículo</h1>

<%= render 'form', veiculo: @veiculo %>

app/views/veiculos/index.html.erb
<h1 class="text-center mt-4">Meus Veículos</h1>

<div class="container">
  <% @veiculos.each do |veiculo| %>
    <div class="row justify-content-md-center">
      <div class="col-7 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body text-left">
            <table>
              <tr>
                <td class="text-right pr-2"><strong>Modelo:</strong></td>
                <td><%= veiculo.modelo.capitalize %></td>
              </tr>
              <tr>
                <td class="text-right pr-2"><strong>Marca:</strong></td>
                <td><%= veiculo.marca.capitalize %></td>
              </tr>
              <tr>
                <td class="text-right pr-2"><strong>Ano:</strong></td>
                <td><%= veiculo.ano %></td>
              </tr>
              <tr>
                <td class="text-right pr-2"><strong>Placa:</strong></td>
                <td><%= veiculo.placa.upcase %></td>
              </tr>
            </table>
            <div class="text-right mt-2">
              <%= link_to 'Editar', edit_veiculo_path(veiculo), class: 'btn btn-info' %>
              <%= link_to 'Excluir', veiculo_path(veiculo), class: 'btn btn-danger', 
                                    method: :delete, data: { confirm: "Tem certeza que deseja excluir essa reserva?" } %>
            </div>
          </div>
          
          <div class="card-footer text-muted">
            <small>
              Criado há <%= time_ago_in_words(veiculo.created_at) %>, 
              modificado há <%= time_ago_in_words(veiculo.updated_at) %>     
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/veiculos/new.html.erb
<h1 class="text-center mt-4">Cadastrar Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>